-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 15:23:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(32) NOT NULL,
  `Registro` DATE NOT NULL,
  `Biografia` VARCHAR(150) NULL,
  `Foto` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacoes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Legenda` VARCHAR(150) NOT NULL,
  `Data` DATETIME NOT NULL,
  `Localizacao` VARCHAR(45) NULL,
  `Conteudo` VARCHAR(150) NOT NULL,
  `Curtidas` BIGINT(11) NOT NULL,
  `Usuarios_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Publicacoes_Usuarios_idx` (`Usuarios_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacoes_Usuarios`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `mydb`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `ID` INT NOT NULL,
  `Texto` VARCHAR(150) NOT NULL,
  `Data` DATETIME NOT NULL,
  `Publicacoes_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Comentarios_Publicacoes1_idx` (`Publicacoes_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Publicacoes1`
    FOREIGN KEY (`Publicacoes_ID`)
    REFERENCES `mydb`.`Publicacoes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguidores` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Publicacoes` VARCHAR(150) NOT NULL,
  `Biografia` VARCHAR(150) NULL,
  `Amigos` VARCHAR(45) NOT NULL,
  `Usuarios_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Seguidores_Usuarios1_idx` (`Usuarios_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Seguidores_Usuarios1`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `mydb`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtags` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtags_has_Publicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtags_has_Publicacoes` (
  `Hashtags_ID` INT NOT NULL,
  `Publicacoes_ID` INT NOT NULL,
  PRIMARY KEY (`Hashtags_ID`, `Publicacoes_ID`),
  INDEX `fk_Hashtags_has_Publicacoes_Publicacoes1_idx` (`Publicacoes_ID` ASC) VISIBLE,
  INDEX `fk_Hashtags_has_Publicacoes_Hashtags1_idx` (`Hashtags_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Hashtags_has_Publicacoes_Hashtags1`
    FOREIGN KEY (`Hashtags_ID`)
    REFERENCES `mydb`.`Hashtags` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hashtags_has_Publicacoes_Publicacoes1`
    FOREIGN KEY (`Publicacoes_ID`)
    REFERENCES `mydb`.`Publicacoes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
