-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 14:51:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_receita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_receita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_receita` DEFAULT CHARACTER SET utf8 ;
USE `bd_receita` ;

-- -----------------------------------------------------
-- Table `bd_receita`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_receita`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_registro` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_receita`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_receita`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_receita`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_receita`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `ingredientes` VARCHAR(500) NOT NULL,
  `instrucoes` VARCHAR(500) NOT NULL,
  `data_publicacao` DATETIME NOT NULL,
  `usuarios_id` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `categorias_id`),
  UNIQUE INDEX `titlo_UNIQUE` (`titulo` ASC),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC),
  INDEX `fk_receitas_usuarios_idx` (`usuarios_id` ASC),
  INDEX `fk_receitas_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_receitas_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bd_receita`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receitas_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `bd_receita`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


